credentialIssuerConfigs:
  - id: kbv
    name: KBV Stub
    authorizeUrl: https://di-ipv-cri-kbv-stub.london.cloudapps.digital/authorize
    tokenUrl: https://di-ipv-cri-kbv-stub.london.cloudapps.digital/token
    credentialUrl: https://di-ipv-cri-kbv-stub.london.cloudapps.digital/credential
    sendIdentityClaims: true
  - id: address
    name: Address Stub
    authorizeUrl: https://di-ipv-cri-address-stub.london.cloudapps.digital/authorize
    tokenUrl: https://di-ipv-cri-address-stub.london.cloudapps.digital/token
    credentialUrl: https://di-ipv-cri-address-stub.london.cloudapps.digital/credential


